theme: jekyll-theme-minimal
title: Alexander's homepage
author: Alexander Lohnau
logo: /assets/img/logo.jpg
description: Blog about variout things, mostly KDE related
# permalink: /:categories/:year/:month/:day/:title
plugins:
  - jekyll-feed
